### ISSUE TITLE
all option in setting button not working

### ISSUE THREAD

**Issue by muhammadarif1** [WSDOT/wsdot-android-app#171]
#### EXPECTED BEHAVIOR 
is supposed to be when the user hits the settings button the user can set this application to what the user wants.
#### ACTUAL BEHAVIOR 
when the user wants to set according to what the user wants all options in the settings section is not functioning and can not be used
#### HOW TO REPRODUCE 
-download WSDOT  fromPLAYSTORE 
- install the app
- click the three dot line at the top right of the app
- select settings
- then press any option and see if the feature does not have any effect
device : android 6.0
browser WSDOT v 5.3.9
#### BUG RECORDING 
https://www.youtube.com/watch?v=UHwzn9FLRro

**Comment by loganSims** [comment]
Thanks for opening an issue.

Could you be more descriptive? Are you running the latest version from the app store or a local build? Also, which versions of Android have you tried?

**Comment by loganSims** [comment]
Thanks for the details!

Currently, the only setting we have is the order of sections in your favorites list. You should be able to drag and drop the items in the settings menu by tapping them from the icon on the right. Can you confirm if the drag and drop is working?

Adding a larger title and bigger tap area for dragging would probably help clarify how that menu works.

**Comment by muhammadarif1** [comment]
its working whit perfectly

**Comment by loganSims** [comment]
Awesome. Going to go ahead and close this issue. I've made a new issue (#172) to address the improvements I mentioned above.
