### ISSUE TITLE
Desktop widgets

### ISSUE THREAD

**Issue by WSDOT** [WSDOT/wsdot-android-app#2]
Add desktop widgets to allow quick access and automatic updates to favorite sections of app.
- Mountain pass weather and conditions
- Travel times
- Travel alerts (Traffic and Ferry)
- Seattle incidents

**Comment by loganSims** [comment]
At the very least I think implementing shortcuts or bookmarks to sections of the app would be helpful. 
For example let users create a home icon that when clicked opens up our traffic map, or a ferry schedule.  Take the functionality of the favorites section and let users add it to their home screen. 

I'm not sure what this is called in Android and if it would actually be a widget.

**Comment by waynedyck** [comment]
Closed because of inactivity.
