### ISSUE TITLE
Runtime error when accessing TrafficMap activity

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-android-app#34]
**java.lang.NullPointerException**
at gov.wa.wsdot.android.wsdot.ui.trafficmap.TrafficMapActivity$CalloutsOverlayTask.onPreExecute(TrafficMapActivity.java:628)
at gov.wa.wsdot.android.wsdot.ui.trafficmap.TrafficMapActivity.onResume(TrafficMapActivity.java:193)

**Comment by waynedyck** [comment]
There are a couple of issues at work here.

- One is the map not being initialized so the call to get the map's bounding latitude and longitude throws a NullPointerException.
- Second is that we are plotting the icon on the map using BitmapDescriptorFactory. BitmapDescriptorFactory is part of Google Play Services and if the user has not updated it in a while then a `java.lang.NullPointerException: IBitmapDescriptorFactory is not initialized` error is thrown.

**Comment by waynedyck** [comment]
As per the Google's documentation on [Setting Up Google Play Services](https://developers.google.com/android/guides/setup), *"...your app should verify the version available before attempting to perform API transactions."*

Even though many of the methods are implemented in the classes, they have no logic in them to show dialogs and inform the user of what actions must be taken to ensure Google Play Services gets updated.

**Comment by loganSims** [comment]
@waynedyck commit c56f0ea13c000be5 may have fixed this issue, correct?

**Comment by waynedyck** [comment]
@loganSims That's what I'm hoping. I say we monitor the crash reports and if we don't see this one appearing in the latest releases of the app then let's consider it closed.

**Comment by loganSims** [comment]
As expected, the error seems to be fixed in versions 4+.
