### ISSUE TITLE
Accessing the Traffic Map places some users in the Atlantic Ocean or elsewhere

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-android-app#36]
When accessing the Traffic Map activity the map for the first time it should center on Seattle. After that it should store the last know location based on either the network or GPS as a saved preference.

Something is wrong with the logic or code given that for a number of users it starts them either in the Atlantic Ocean or elsewhere.

**Comment by loganSims** [comment]
No new reports lately, closing issue for now.
