### ISSUE TITLE
Updating To Play Services 8.3 And Up Causes App To Crash

### ISSUE THREAD

**Issue by loganSims** [WSDOT/wsdot-android-app#44]
App isn't asking user for permission to access location and crashes.

`java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION`

**Comment by waynedyck** [comment]
This only appears to be an issue on Android 6.x devices running API level 23.

**Comment by loganSims** [comment]
I believe [this](https://code.google.com/p/gmaps-api-issues/issues/detail?id=8906) describes the issue.
Working on fix now.

**Comment by loganSims** [comment]
Implementing solution from [here] (https://developers.google.com/maps/documentation/android-api/location#request_runtime_permissions) under "Request runtime permissions".
