### ISSUE TITLE
Cameras not updated when new cameras added to feed

### ISSUE THREAD

**Issue by loganSims** [WSDOT/wsdot-android-app#89]
Need to look into how cameras get updated in the app.

**Comment by waynedyck** [comment]
I'm fairly sure cameras are cached within the app for a week at a time. If a new camera gets added to the database a user potentially won't see it in the app for a week at most. The camera JSON feed is updated once a day in the morning I think.

**Comment by loganSims** [comment]
That seems like a reasonable update cycle. I image cameras aren't added that often. We had a user email asking why cameras weren't on the map. I noticed they weren't on the nexus as well. Clearing the app data pulled them in just fine.

**Comment by loganSims** [comment]
I think there needs to be a way for users to refresh cameras themselves. This way when users notice new cameras online that aren't in the app they can pull them in without clearing app data and loosing favorites.

**Comment by loganSims** [comment]
This has been moved into issue #98.
